package CompFund2.Module5.Assignment5;

import java.util.SortedSet;
//import java.util.TreeSet;

/**
 * Provides a factory method for creating word search games. 
 */
public class TestWordSearchGameFactory {

    /**
     * Returns an instance of a class that implements the WordSearchGame
     * interface.
     */
    public static WordSearchGame createGame() {
        return new GameEngine();
        // You must return an instance of your solution class here.
    }

    public static void main(String[] args) {
        WordSearchGame test = createGame();
        System.out.println(test.getBoard());
        
        test.loadLexicon("ALBEE" + "\n" + "Alepot" + "\n" + "ALEPOTS" + "\n" + "LENT" + "\n" + "LEAP" + "\n" + "TIGER");
        //System.out.println(test.isOnBoard("LENT"));
        //System.out.println(test.isOnBoard("ALEPOT"));
        //System.out.println(test.isOnBoard("LEAP"));

        //String[] testA = {"TIGER"};
        //String[] testB = {"H","A","I","X","R","E","O","O","Y","QU","E","O","H","R","F","O",};
        //test.setBoard(testB);
        //System.out.println(test.getBoard());
        SortedSet<String> testSet = test.getAllScorableWords(3);
        System.out.println(testSet);
        System.out.println(test.getScoreForWords(testSet, 4));


        String testS = """
        gyroscope
        habeas
        haberdashery
        habit
        habitant
        habitat
        habitation
        habitual
        habituate
        hacienda
        hack
        hackberry
        hackle
        hackmatack
        hackney
        hackneyed
        hacksaw
        had
        haddock
        hadron
        hafnium
        haggard
        haggle
        haiku
        hail
        hailstone
        hailstorm
        hair
        haircut
        hairdo
        hairpin
        hairy
        halcyon
        hale
        half
        halfback
        halfhearted
        halfway
        halibut
        halide
        halite
        hall
        hallelujah
        hallmark
        hallow
        hallucinate
        hallway
        halma
        halo
        halocarbon
        halogen
        halt
        halvah
        halve
        ham
        hamburger
        hamlet
        hammerhead
        hammock
        hamper
        hamster
        hand
        handbag
        handbook
        handclasp
        handcuff
        handful
        handgun
        handhold
        handicap
        handicapped
        handicapper
        handicapping
        handicraft
        handicraftsman
        handicraftsmen
        handiwork
        handkerchief
        handle
        handleable
        handlebar
        handline
        handmade
        handmaiden
        handout
        handset
        handshake
        handsome
        handspike
        handstand
        handwaving
        handwrite
        handwritten
        handy
        handyman
        handymen
        hang
        hangable
        hangar
        hangman
        hangmen
        hangout
        hangover
        hank
        hansom
        hap
        haphazard
        haploid
        haploidy
        haplology
        happen
        happenstance
        happy
        harangue
        harass
        harbinger
        hard
        hardbake
        hardboard
        hardboiled
        hardcopy
        harden
        hardhat
        hardscrabble
        hardtack
        hardtop
        hardware
        hardwood
        hardworking
        hardy
        hare
        harelip
        harem
        hark
        harm
        harmful
        harmonic
        harmonica
        harmonious
        harmony
        harness
        harp
        harpoon
        harpsichord
        harrow
        harry
        harsh
        harshen
        hart
        harvest
        harvestman
        hash
        hashish
        hasp
        hassle
        hast
        haste
        hasten
        hasty
        hat
        hatch
        hatchet
        hatchway
        hate
        hateful
        hater
        hath
        hatred
        haughty
        haul
        haulage
        haunch
        haunt
        have
        haven
        havoc
        haw
        hawk
        hawthorn
        hay
        hayfield
        haystack
        hayward
        hazard
        hazardous
        haze
        hazel
        hazelnut
        hazy
        head
        headache
        headboard
        headdress
        headland
        headlight
        headline
        headmaster
        headphone
        headquarter
        headquarters
        headroom
        headset
        headsman
        headsmen
        headstand
        headstone
        headstrong
        headwall
        headwater
        headway
        headwind
        heady
        heal
        health
        healthful
        healthy
        heap
        hear
        heard
        hearken
        hearsay
        hearse
        heart
        heartbeat
        heartbreak
        hearten
        heartfelt
        hearth
        hearty
        heat
        heater
        heath
        heathen
        heathenish
        heave
        heaven
        heavenward
        heavy
        heavyweight
        hebephrenic
        hecatomb
        heck
        heckle
        hectic
        hector
        hedge
        hedgehog
        hedonism
        hedonist
        heed
        heel
        heft
        hefty
        hegemony
        heigh
        height
        heighten
        heir
        heiress
        held
        helical
        helicopter
        heliocentric
        heliotrope
        helium
        helix
        hell
        hellbender
        hellebore
        hellfire
        hellgrammite
        hellish
        hello
        helm
        helmet
        helmsman
        helmsmen
        help
        helpful
        helpmate
        hem
        hematite
        hemisphere
        hemispheric
        hemlock
        hemoglobin
        hemolytic
        hemorrhage
        hemorrhoid
        hemosiderin
        hemp
        hen
        henbane
        hence
        henceforth
        henchman
        henchmen
        henequen
        henpeck
        henry
        hepatica
        hepatitis
        heptane
        her
        herald
        herb
        herd
        herdsman
        here
        hereabout
        hereafter
        hereby
        hereditary
        heredity
        herein
        hereinabove
        hereinafter
        hereinbelow
        hereof
        heresy
        heretic
        hereto
        heretofore
        hereunder
        hereunto
        herewith
        heritable
        heritage
        hermeneutic
        hermetic
        hermitian
        hero
        heroes
        heroic
        heroin
        heroine
        heroism
        heron
        herpes
        herpetology
        herringbone
        herself
        hertz
        hesitant
        hesitate
        hesitater
        heterocyclic
        heterodyne
        heterogamous
        heterogeneity
        heterogeneous
        heterosexual
        heterozygous
        heuristic
        hew
        hewn
        hex
        hexachloride
        hexadecimal
        hexafluoride
        hexagon
        hexagonal
        hexameter
        hexane
        hey
        heyday
        hiatus
        hibachi
        hibernate
        hick
        hickory
        hid
        hidalgo
        hidden
        hide
        hideaway
        hideous
        hideout
        hierarchal
        hierarchic
        hierarchy
        hieratic
        hieroglyphic
        hifalutin
        high
        highball
        highboy
        highest
        highfalutin
        highhanded
        highland
        highlight
        highroad
        hightail
        highway
        highwayman
        highwaymen
        hijack
        hijinks
        hike
        hilarious
        hilarity
        hill
        hillbilly
        hillman
        hillmen
        hillock
        hillside
        hilltop
        hilly
        hilt
        hilum
        him
        himself
        hind
        hindmost
        hindrance
        hindsight
        hinge
        hint
        hinterland
        hip
        hippo
        hippodrome
        hippopotamus
        hippy
        hipster
        hire
        hireling
        hirsute
        his
        hiss
        histamine
        histidine
        histochemic
        histochemistry
        histogram
        histology
        historian
        historic
        historiography
        history
        histrionic
        hit
        hitch
        hither
        hitherto
        hive
        hoagie
        hoagy
        hoar
        hoard
        hoarfrost
        hoarse
        hob
        hobble
        hobby
        hobbyhorse
        hobgoblin
        hobo
        hoc
        hock
        hockey
        hocus
        hodge
        hodgepodge
        hoe
        hog
        hogan
        hogging
        hoi
        hold
        holden
        holdout
        holdover
        holdup
        hole
        holeable
        holiday
        holler
        hollow
        hollowware
        holly
        hollyhock
        holmium
        holocaust
        hologram
        holography
        holster
        holt
        holystone
        homage
        home
        homebound
        homebuild
        homebuilder
        homebuilding
        homecome
        homecoming
        homeland
        homemade
        homemake
        homeomorph
        homeomorphic
        homeopath
        homeostasis
        homeown
        homeowner
        homesick
        homestead
        homeward
        homework
        homicidal
        homicide
        homily
        homo
        homogenate
        homogeneity
        homogeneous
        homologous
        homologue
        homology
        homomorphic
        homomorphism
        homonym
        homophobia
        homosexual
        homotopy
        homozygous
        homunculus
        hondo
        hone
        honest
        honesty
        honey
        honeybee
        honeycomb
        honeydew
        honeymoon
        honeysuckle
        hong
        honk
        honoraria
        honorarium
        honorary
        honoree
        honorific
        hooch
        hood
        hoodlum
        hoof
        hoofmark
        hook
        hookup
        hookworm
        hooligan
        hoop
        hoopla
        hoosegow
        hoot
        hooves
        hop
        hope
        hopeful
        hopple
        hopscotch
        horde
        horehound
        horizon
        horizontal
        hormone
        horn
        hornbeam
        hornblende
        hornet
        hornmouth
        horntail
        hornwort
        horny
        horology
        horoscope
        horrendous
        horrible
        horrid
        horrify
        horror
        horse
        horseback
        horsedom
        horseflesh
        horsefly
        horsehair
        horseman
        horsemen
        horseplay
        horsepower
        horseshoe
        horsetail
        horsewoman
        horsewomen
        horticulture
        hose
        hosiery
        hospice
        hospitable
        hospital
        host
        hostage
        hostelry
        hostess
        hostile
        hostler
        hot
        hotbed
        hotbox
        hotel
        hotelman
        hothead
        hothouse
        hotrod
        hotshot
        hough
        hound
        hour
        hourglass
        house
        houseboat
        housebreak
        housebroken
        housefly
        household
        housekeep
        housewares
        housewife
        housewives
        housework
        hove
        hovel
        hover
        how
        howdy
        however
        howl
        howsoever
        howsomever
        hoy
        hoyden
        hoydenish
        hub
        hubbub
        hubby
        hubris
        huck
        huckleberry
        huckster
        huddle
        hue
        hued
        huff
        hug
        huge
        hugging
        huh
        hulk
        hull
        hum
        human
        humane
        humanitarian
        humanoid
        humble
        humerus
        humid
        humidify
        humidistat
        humiliate
        humility
        hummingbird
        hummock
        humorous
        hump
        humpback
        humpty
        humus
        hunch
        hundred
        hundredfold
        hundredth
        hung
        hungry
        hunk
        hunt
        hurdle
        hurl
        hurley
        hurrah
        hurray
        hurricane
        hurry
        hurt
        hurtle
        hurty
        husband
        husbandman
        husbandmen
        husbandry
        hush
        husky
        hustle
        hut
        hutch
        huzzah
        hyacinth
        hyaline
        hybrid
        hydra
        hydrangea
        hydrant
        hydrate
        hydraulic
        hydride
        hydro
        hydrocarbon
        hydrochemistry
        hydrochloric
        hydrochloride
        hydrodynamic
        hydroelectric
        hydrofluoric
        hydrogen
        hydrogenate
        hydrology
        hydrolysis
        hydrometer
        hydronium
        hydrophilic
        hydrophobia
        hydrophobic
        hydrosphere
        hydrostatic
        hydrothermal
        hydrous
        hydroxide
        hydroxy
        hydroxyl
        hydroxylate
        hyena
        hygiene
        hygrometer
        hygroscopic
        hying
        hymen
        hymn
        hymnal
        hyperbola
        hyperbolic
        hyperboloid
        hyperboloidal
        hypertensive
        hyphen
        hyphenate
        hypnosis
        hypnotic
        hypoactive
        hypochlorite
        hypochlorous
        hypocrisy
        hypocrite
        hypocritic
        hypocritical
        hypocycloid
        hypodermic
        hypophyseal
        hypotenuse
        hypothalamic
        hypothalamus
        hypotheses
        hypothesis
        hypothetic
        hypothyroid
        hysterectomy
        hysteresis
        hysteria
        hysteric
        hysteron
        iambic
        ibex
        ibid
        ibis
        ice
        iceberg
        icebox
        iceland""";

        test.loadLexicon(testS);
        String[] testB = {"H","A","I","X","R","E","O","O","Y","QU","E","O","H","R","F","O",};
        test.setBoard(testB);
        testSet = test.getAllScorableWords(3);
        System.out.println(testSet);
        System.out.println(test.getScoreForWords(testSet, 3));
    }

}
